### PR TITLE
Added installation instructions for distrobox

### PR DESCRIPTION
**Pull request by TKK13909**
I just threw these instructions together in about an hour so please test this on multiple systems to make sure it works. It works on my system running Fedora Kinoite 40.

### CODE REVIEW

**Comment by Bali10050** [comment]
Thank you, I'll try installing it onto a virual machine to see if there's anything missing, then if it somewhat works I'll merge it.

**Comment by TKK13909** [comment]
For it to work on my system, I put a file called `localthemes.sh` in my `~/.config/plasma-workspace/env` directory with the following contents: `export QT_PLUGIN_PATH=$HOME/.local/lib64/plugins:$QT_PLUGIN_PATH`.

**Comment by Bali10050** [comment]
I couldn't even start installing it on my vm, it seems that this Fedora Kinoite doesn't like me. I tried setting it up 3 times, but the install kept breaking the vm for me, so I haven't even gotten into the testing the code part. If you say you're about 90% sure this works, I'll merge it

**Comment by TKK13909** [comment]
I just run this on a fresh user account on my system (this should also work on literally any distro with distrobox available) and it worked perfectly. Feel free to add the bit about defining the environment variable in a script in `~/.config/plasma-workspace/env` to the final merge if you can.

**Comment by Bali10050** [comment]
I'll merge this, and we'll fix the issues later. Anyways, thank you guys!

**Comment by TKK13909** [comment]
> Running this on an Arch VM.
> 
> `distrobox create --name lightly --image fedora-toolbox:40` Image fedora-toolbox:40 not found. Do you want to pull the image now? [Y/n]: y Error: short-name "fedora-toolbox:40" did not resolve to an alias and no unqualified-search registries are defined in "/etc/containers/registries.conf"
> 
> Would be better to update the cmd and use the FQDN of the registry.
> 
> `distrobox create --name lightly --image registry.fedoraproject.org/fedora-toolbox:40`

Yes that would probably be best.

**Pull request merged**
