### PR TITLE
adding missing dependencies for arch linux

### PR DESCRIPTION
**Pull request by Heus-Sueh**

### CODE REVIEW

**Comment by Bali10050** [comment]
Are you sure that those dependencies are missing? I'm using it from arch and I haven't run into any problems yet

**Comment by Heus-Sueh** [comment]
> Are you sure that those dependencies are missing? I'm using it from arch and I haven't run into any problems yet

I tried to run the build without these dependencies and cmake complained, I'm not using KDE Plasma, that must be why it complained

**Comment by Bali10050** [comment]
They all seem to be included in plasma, so you're probably right

**Comment by Bali10050** [comment]
Also, I forgot to say thanks!

**Pull request merged**
